on:
  push:
jobs:
  mail_on_push:
    runs-on: windows-latest
    steps:
      - name: Send mail to this address
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}  
          password: ${{ secrets.MAIL_PASSWORD }}  
          subject: 'ALERT, we have detected a commit in ${{ github.repository }}'
          body: |
            Hello Erwin,

            A commit has been detected!

            Commit created by ${{ github.event.pusher.name }}
          to: "ervin.sults@gmail.com"  
          from: ${{ secrets.MAIL_USERNAME }}  
